#!/bin/sh
#PBS -N ADMIXTURE
#PBS -S /bin/bash
#PBS -l mem=2gb
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1

ADMIXTURE="/home/cliu7/utils/admixture_linux-1.3.0/admixture"
scratch_data="/scratch/cliu7/ancient_ACA/data"
output_path="/home/cliu7/ancient_ACA/output/admixture"

###################
## run ADMIXTURE ##
###################

K=$1
r=$2
data_admixture_subset="${scratch_data}/intermediate/illumina_all_merged.description"
prefix=$(echo $data_admixture_subset | rev | cut -d'/' -f1 | rev)

mkdir /scratch/cliu7/${prefix}_${K}_${r}
cd /scratch/cliu7/${prefix}_${K}_${r}

$ADMIXTURE -s ${RANDOM} $data_admixture_subset.bed $K
mv ${prefix}.${K}.Q ${output_path}/${prefix}.K${K}r${r}.Q
