#!/bin/sh
#PBS -N D-stat
#PBS -S /bin/bash
#PBS -l mem=5gb
#PBS -l walltime=24:00:00

module load gcc/6.2.0
module load gsl/2.3
module load openblas/0.2.19

compute_f4="/scratch/cliu7/AdmixTools/bin/qpDstat"
input_path="/scratch/cliu7/ancient_ACA/data/intermediate"
par_path="/home/cliu7/ancient_ACA/data/params/fstats"
#output_path="/home/cliu7/ancient_ACA/output/fstats"
output_path="/scratch/cliu7"

MAKE_PARAM_FILE(){
    input_prefix="${input_path}/$1"
    table_prefix="${par_path}/$2"
    PAR=$3
    echo "genotypename: ${input_prefix}.geno" > $PAR
    echo "snpname: ${input_prefix}.snp" >> $PAR
    echo "indivname: ${input_prefix}.ind" >> $PAR
    echo "popfilename: ${table_prefix}.txt" >> $PAR
    echo "printsd: YES" >> $PAR
}

par=$(mktemp par.XXXXX)
MAKE_PARAM_FILE HO_all_merged.deepAncestry worldwide_ancient_relationship $par
output_prefix="${output_path}/worldwide_ancient_relationship.$1_$2"
$compute_f4 -p $par -L $1 -H $2 > ${output_prefix}.log 
rm $par
grep result ${output_prefix}.log | awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> ${output_prefix}.table.txt

